"""Add stock and product_description to Product

Revision ID: 2035b3c87051
Revises: 926d0f7e9e93
Create Date: 2026-02-20 16:11:24.294176

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2035b3c87051"
down_revision: Union[str, Sequence[str], None] = "926d0f7e9e93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product", sa.Column("stock", sa.Integer(), server_default="0", nullable=False))
    op.add_column(
        "product", sa.Column("product_description", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "product_description")
    op.drop_column("product", "stock")
    # ### end Alembic commands ###
