"""Add SiteSettings table

Revision ID: 926d0f7e9e93
Revises: 5400fcb7b5d6
Create Date: 2026-02-02 15:10:03.403573

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "926d0f7e9e93"
down_revision: Union[str, Sequence[str], None] = "5400fcb7b5d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sitesettings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("price_range_min", sa.Integer(), nullable=False),
        sa.Column("price_range_max", sa.Integer(), nullable=False),
        sa.Column("price_range_step", sa.Integer(), nullable=False),
        sa.Column("sorting_options", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sitesettings")
    # ### end Alembic commands ###
